### PR TITLE
Set default DPI to 96 on X11 (in case the screen doesn't have sub pixel)

### PR DESCRIPTION
**Pull request by locriacyber**
My display doesn't have DPI info. Without this patch the program won't start.

### CODE REVIEW

**Comment by fabioarnold** [comment]
Thanks for your PR! I need to check this out once I'm home and have access to my Linux machine.

**Comment by locriacyber** [comment]
The SDL default DPI is blurry for some reason.

```
> xrandr --verbose | grep -i subpixel
	Subpixel:   unknown
	Subpixel:   unknown
	Subpixel:   unknown
	Subpixel:   unknown
	Subpixel:   unknown
	Subpixel:   no subpixels
	Subpixel:   unknown
```

**Comment by fabioarnold** [comment]
Finally tried on my machine and made a few minor adjustments. Thanks again for your contribution!

**Comment by locriacyber** [comment]
I think you un-fixed it.

**Comment by fabioarnold** [comment]
Sounds like you have a high DPI display. Isn't the app a bit small at 1x scale?
I don't understand why it's blurry. Maybe because the scale isn't an integer. Can you take a screenshot?
Could we resolve this issue more easily on Discord?

**Comment by locriacyber** [comment]
The app looks bigger than expected. My display doesn't have subpixel, so 1 physical pixel = 1 logical pixel.

**Comment by fabioarnold** [comment]
I see. That's because SDL2 reports the physical DPI of your display (resolution/inches), not the logical DPI. This is mentioned in a comment and a known issue of SDL2 on Linux.

I recommend putting a file $HOME/.Xresources with the following contents in your home directory:
```
Xft.dpi: 96
```

**Comment by locriacyber** [comment]
That's not how it usually works on Linux... You simply don't use DPI.

Also, you Discord ID is incomplete. I need the #1234 at the end

**Comment by fabioarnold** [comment]
> You simply don't use DPI.
Yes, you do if you have high DPI monitor. And I happen to own one.

**Comment by locriacyber** [comment]
You use DPI to know how many pixels are a cm/inch.  

above, DPI: 96  
below, DPI: 144  
image

**Comment by fabioarnold** [comment]
Confirmed cdb60eb38085c1aafdf82ebeee6581b327467cbd fixes the issue via Discord.

**Pull request merged**
